const dogs = [
  {
    name: "Maro-chan",
    avatar: "images/dog-maro-chan.jpg",
    age: 25,
    bio: "Am a happy sheeb dog, like chewing grass",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Dean",
    avatar: "images/dog-dean.jpg",
    age: 20,
    bio: "Love a good hot chocolate on a nice snowy day",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Rex",
    avatar: "images/dog-rex.jpg",
    age: 25,
    bio: "Art. Literature. Natural wine. Yoga.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Kuro",
    avatar: "images/dog-kuro.jpg",
    age: 40,
    bio: "I don't like being outside, I'd rather nap",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Bella",
    avatar: "images/dog-bella.jpg",
    age: 43,
    bio: "Yup, that's my owner. U can meet him if you want",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Teddy",
    avatar: "images/dog-teddy.jpg",
    age: 30,
    bio: "How you doin?",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Steve",
    avatar: "images/dog-steve.jpg",
    age: 15,
    bio: "I LOVE playing fetch! It's my favourite hobby",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
];

export default dogs;
